// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAay6e1HZTUbjIVsKuUOFmoFYPmHAr_VdI',
    appId: '1:508121969318:web:f978f4f0af0745782e3a67',
    messagingSenderId: '508121969318',
    projectId: 'gkasse-zsoft',
    authDomain: 'gkasse-zsoft.firebaseapp.com',
    storageBucket: 'gkasse-zsoft.appspot.com',
    measurementId: 'G-8ZNQBRK90T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0NQ0A-9vkTFiuRBlmiB4zwdXP5hHWoZw',
    appId: '1:508121969318:android:86c66bdafb453df92e3a67',
    messagingSenderId: '508121969318',
    projectId: 'gkasse-zsoft',
    storageBucket: 'gkasse-zsoft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACn_jxUUcOD5Jy8c0NCmEDaJHpzI7xg1A',
    appId: '1:508121969318:ios:e25235b8a2b42dae2e3a67',
    messagingSenderId: '508121969318',
    projectId: 'gkasse-zsoft',
    storageBucket: 'gkasse-zsoft.appspot.com',
    iosBundleId: 'com.example.gKasse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACn_jxUUcOD5Jy8c0NCmEDaJHpzI7xg1A',
    appId: '1:508121969318:ios:099f665472efd5de2e3a67',
    messagingSenderId: '508121969318',
    projectId: 'gkasse-zsoft',
    storageBucket: 'gkasse-zsoft.appspot.com',
    iosBundleId: 'com.example.gKasse.RunnerTests',
  );
}
