name: eierapp
description: Eier KochApp.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.0
  flutter:
    sdk: flutter
  
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/0min.png
    - assets/1min.png
    - assets/2min.png
    - assets/3min.png
    - assets/5min.png
    - assets/7min.png
    - assets/9min.png
    - assets/11min.png
    - assets/13min.png
    - assets/15min.png
    - assets/stop_timer.mp3
