name: test_app3
description: Morsecode Generator.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon_ios1024.png"
  remove_alpha_ios: true