name: g_kasse
description: G-Kasse.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  categorized_dropdown: ^1.0.0
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  cloud_firestore:
  flutter:
    sdk: flutter
  flutter_icon_snackbar: ^1.1.4
  flutter_lints: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
#  - assets/data/data.json
  - assets/logo_large.png
  - assets/logo_small.png
  - assets/images/image_placeholder.png
  - assets/images/no_logo_image.png
  
