name: g_kasse
description: G-Kasse.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  categorized_dropdown: ^1.0.0
  firebase_analytics: ^10.8.5
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  flutter:
    sdk: flutter
  flutter_icon_snackbar: ^1.1.4
  flutter_lints: ^3.0.1
  hive: ^2.2.3
  hive_flutter: 1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.2
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
  - assets/logo/logo_large.png
  - assets/logo/logo_small.png
  - assets/images/image_placeholder.png
  - assets/images/no_logo_image.png
  